version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "$APP_DB_PORT:$APP_DB_PORT"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "$APP_PORT:$APP_PORT"
    depends_on:
      - db
    environment:
      DATABASE_URL: "$DATABASE_URL"

volumes:
  db_data: