version: '3.8'

services:
  db:
    image: postgres:13
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  db_data:
